apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
data:
  application.properties: |
    aggregator.temperature-url=http://temperature-service:8080/temperature
    aggregator.humidity-url=http://humidity-service:8080/humidity
    aggregator.temperature-unit=K