apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature
  template:
    metadata:
      labels:
        app: temperature
    spec:
      containers:
        - name: temperature
          image: temperature-microservice:1.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: readings-volume
              mountPath: /config
      volumes:
        - name: readings-volume
          configMap:
            name: temperature-readings
